export const FILTER = 'FILTER'
export const GET_SHOE_BY_ID = 'GET_SHOE_BY_ID'
export const API_URL = 'http://localhost:3001'
export const FILTER_RANGE = 'FILTER_RANGE'
export const FILTER_LOCAL = 'FILTER_LOCAL'
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const ORDER = 'ORDER'
export const POST_SHOE = 'POST_SHOE'
